CalendarioFutbol/Controllers/JuegosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CalendarioFutbol.DataAccess;
using CalendarioFutbol.Models;

namespace CalendarioFutbol.Controllers
{
    public class JuegosController : Controller
    {
        private CalendarioFutbolEntities db = new CalendarioFutbolEntities();

        // GET: Juegos
        public ActionResult Index( int id)
        {
            // Obtenemos los jugadores del equpo
            var TorneoJuegos = db.Juegos.Where(x => x.TorneoID == id).ToList();

            // Obtenemos los datos del torneo en base a su id.
            ViewData["Torneo"] = db.Torneo.Find(id).Nombre;
            ViewData["TorneoID"] = id;

            // Obtenemos la lista de los equipos
            var equipos = db.Equipos.Select(x => new EquipoLista { ID = x.EquipoID, Nombre = x.Nombre }).ToList();
            ViewData["Equipos"] = equipos;

            return View(TorneoJuegos);
        }

        // POST: Juegos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JuegosID,TorneoID,EquipoLocalID,EquipoVisitanteID,FechaHoraPartido")] Juegos juegos)
        {
            if (ModelState.IsValid)
            {
                db.Juegos.Add(juegos);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = juegos.TorneoID });
            }

            return View(juegos);
        }

        // Juegos/Delete/5
        public ActionResult Delete(int id)
        {
            Juegos juegos = db.Juegos.Find(id);
            var torneoID = juegos.TorneoID;
            db.Juegos.Remove(juegos);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = torneoID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CalendarioFutbol/Controllers/TorneosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CalendarioFutbol.DataAccess;
using CalendarioFutbol.Models;

namespace CalendarioFutbol.Controllers
{
    public class TorneosController : Controller
    {
        private CalendarioFutbolEntities db = new CalendarioFutbolEntities();

        // GET: Torneos
        public ActionResult Index()
        {
            return View(db.Torneo.ToList());
        }

        // GET: Torneos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Torneo torneo = db.Torneo.Find(id);
            if (torneo == null)
            {
                return HttpNotFound();
            }
            return View(torneo);
        }

        // GET: Torneos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Torneos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TorneoID,Nombre")] Torneo torneo)
        {
            if (ModelState.IsValid)
            {
                db.Torneo.Add(torneo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(torneo);
        }

        // GET: Torneos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Torneo torneo = db.Torneo.Find(id);
            if (torneo == null)
            {
                return HttpNotFound();
            }
            return View(torneo);
        }

        // POST: Torneos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TorneoID,Nombre")] Torneo torneo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(torneo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(torneo);
        }

        // GET: Torneos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Torneo torneo = db.Torneo.Find(id);
            if (torneo == null)
            {
                return HttpNotFound();
            }
            return View(torneo);
        }

        // POST: Torneos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Torneo torneo = db.Torneo.Find(id);
            db.Torneo.Remove(torneo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Tablero(int id)
        {
            var torneo = new TableroVista();
            torneo.NombreTorneo = db.Torneo.Find(id).Nombre;
            torneo.JuegosTorneo = new List<JuegosLista>();
            var juegos = db.Juegos.Where(x => x.TorneoID == id).ToList();
            juegos.ForEach(delegate (Juegos juegos1) {
                torneo.JuegosTorneo.Add(new JuegosLista()
                {
                    Local = db.Equipos.Find(juegos1.EquipoLocalID).Nombre,
                    Imagenlocal = db.Equipos.Find(juegos1.EquipoLocalID).Imagen,
                    Visitante = db.Equipos.Find(juegos1.EquipoVisitanteID).Nombre,
                    ImagenVisitante = db.Equipos.Find(juegos1.EquipoVisitanteID).Imagen,
                    Horario = juegos1.FechaHoraPartido.ToString("dd/MM/yyyy HH:mm")
                });
            });
            return View(torneo);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CalendarioFutbol/Views/Torneos/Create.cshtml
@model CalendarioFutbol.DataAccess.Torneo

@{
    ViewBag.Title = "Nuevo Torneo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nuevo torneo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Nuevo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Torneos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CalendarioFutbol/Views/Torneos/Delete.cshtml
@model CalendarioFutbol.DataAccess.Torneo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Torneo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CalendarioFutbol/Views/Torneos/Details.cshtml
@model CalendarioFutbol.DataAccess.Torneo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Torneo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TorneoID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CalendarioFutbol/Views/Torneos/Edit.cshtml
@model CalendarioFutbol.DataAccess.Torneo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Torneo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TorneoID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CalendarioFutbol/Views/Torneos/Index.cshtml
@model IEnumerable<CalendarioFutbol.DataAccess.Torneo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.TorneoID }) |
                @Html.ActionLink("Agregar Juegos", "index", "Juegos", new { id = item.TorneoID }, null) |
                @Html.ActionLink("Tablero", "Tablero", new { id = item.TorneoID }, null) |
                @Html.ActionLink("Delete", "Delete", new { id = item.TorneoID })
            </td>
        </tr>
    }

</table>

CalendarioFutbol/Views/Torneos/Tablero.cshtml
@model CalendarioFutbol.Models.TableroVista

@{
    ViewBag.Title = "Tablero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2 class="p-5 text-center">@Model.NombreTorneo</h2>
    @foreach (var item in @Model.JuegosTorneo)
    {
        <div class="card">
            <div class="card-body">
                <div class="row align-items-md-center">
                    <div class="col"><span>@item.Local</span>  -  <img src="@Url.Content(item.Imagenlocal)" class="rounded" width="30" height="30"></div>
                    <div class="col text-center"><h4> VS </h4></div>
                    <div class="col text-right"><img src="@Url.Content(item.ImagenVisitante)" class="rounded" width="30" height="30">  -  <span>@item.Visitante</span></div>
                </div>
                <div class="row align-items-md-center">
                    <div class="col text-center"><h5><strong>@item.Horario</strong></h5></div>
                </div>
            </div>
        </div>
    }
</div>