CalendarioFutbol/Controllers/EquiposController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CalendarioFutbol.DataAccess;

namespace CalendarioFutbol.Controllers
{
    public class EquiposController : Controller
    {
        private CalendarioFutbolEntities db = new CalendarioFutbolEntities();

        // GET: Equipos
        public ActionResult Index()
        {
            return View(db.Equipos.ToList());
        }

        // GET: Equipos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipos equipos = db.Equipos.Find(id);
            if (equipos == null)
            {
                return HttpNotFound();
            }
            return View(equipos);
        }

        // GET: Equipos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Equipos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EquipoID,Nombre,Imagen,Eliminado")] Equipos equipos)
        {
            if (ModelState.IsValid)
            {
                //todos los equipos al crearse no son eliminados
                equipos.Eliminado = false;

                db.Equipos.Add(equipos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(equipos);
        }

        // GET: Equipos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipos equipos = db.Equipos.Find(id);
            if (equipos == null)
            {
                return HttpNotFound();
            }
            return View(equipos);
        }

        // POST: Equipos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EquipoID,Nombre,Imagen,Eliminado")] Equipos equipos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(equipos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(equipos);
        }

        // GET: Equipos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipos equipos = db.Equipos.Find(id);
            if (equipos == null)
            {
                return HttpNotFound();
            }
            return View(equipos);
        }

        // POST: Equipos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // No existe la elimnación Fisca solo logica
            Equipos equipos = db.Equipos.Find(id);
            equipos.Eliminado = true;
            db.Entry(equipos).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CalendarioFutbol/Controllers/EquiposJugadoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CalendarioFutbol.DataAccess;
using CalendarioFutbol.Models;

namespace CalendarioFutbol.Controllers
{
    public class EquiposJugadoresController : Controller
    {
        private CalendarioFutbolEntities db = new CalendarioFutbolEntities();

        // GET: EquiposJugadores
        public ActionResult Index(int id)
        {
            // Obtenemos los jugadores del equpo
            var EquiposJugadores = db.EquiposJugadores.Where(x => x.EquipoID == id).ToList();

            // Obtenemos los datos del equipo en base a su id.
            ViewData["Equipo"] = db.Equipos.Find(id).Nombre;
            ViewData["EquipoID"] = id;

            // Obtenemos la lista de los jugadores
            var jugadores = db.Jugadores.Select(x => new JugadoresLista { ID = x.JugadorID, Nombre = x.Nombre }).ToList();

            // Obtenemos los que se van a mostrar en la tabla
            ViewData["Jugadores"] = jugadores.Where(x => (EquiposJugadores.Select(y => y.JugadorID).Contains(x.ID))).ToList();

            // Removemos los jugadores ya seleccionados en el equipo
            jugadores.RemoveAll(x => (EquiposJugadores.Select(y => y.JugadorID).Contains(x.ID)));
            ViewData["JugadoresFiltrados"] = jugadores;

            return View(EquiposJugadores);
        }

        // POST: EquiposJugadores/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EquipoJugadorID,EquipoID,JugadorID")] EquiposJugadores equiposJugadores)
        {
            if (ModelState.IsValid)
            {
                db.EquiposJugadores.Add(equiposJugadores);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = equiposJugadores.EquipoID });
            }

            return View(equiposJugadores);
        }

        // Delete: EquiposJugadores/Delete/5
        public ActionResult Delete(int id)
        {
            EquiposJugadores equiposJugadores = db.EquiposJugadores.Find(id);
            var EquipoId = equiposJugadores.EquipoID;
            db.EquiposJugadores.Remove(equiposJugadores);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = EquipoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CalendarioFutbol/Views/Equipos/Create.cshtml
@model CalendarioFutbol.DataAccess.Equipos

@{
    ViewBag.Title = "Nuevo Equipo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nuevo Equipo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Equipo:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Nuevo equipo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Equipos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CalendarioFutbol/Views/Equipos/Delete.cshtml
@model CalendarioFutbol.DataAccess.Equipos

@{
    ViewBag.Title = "Baja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Baja</h2>

<h3>Deseas dar de baja este equipo?</h3>
<div>
    <h4>Equipo:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Dar de Baja" class="btn btn-default" /> |
            @Html.ActionLink("Lista de Equipos", "Index")
        </div>
    }
</div>

CalendarioFutbol/Views/Equipos/Details.cshtml
@model CalendarioFutbol.DataAccess.Equipos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Equipos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Eliminado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eliminado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EquipoID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CalendarioFutbol/Views/Equipos/Edit.cshtml
@model CalendarioFutbol.DataAccess.Equipos

@{
    ViewBag.Title = "Editar Equipo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Equipo:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EquipoID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Eliminado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Eliminado, htmlAttributes:  new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Eliminado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Equipos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CalendarioFutbol/Views/Equipos/Index.cshtml
@model IEnumerable<CalendarioFutbol.DataAccess.Equipos>

@{
    ViewBag.Title = "Equipos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Equipos Registrados</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Eliminado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Imagen)
        </td>
        <td>
            @Html.CheckBoxFor(modelItem => item.Eliminado, htmlAttributes: new {@class="form-control",  @disabled = "disabled"})
        </td>
        <td>
            @Html.ActionLink("Editar equipo", "Edit", new { id = item.EquipoID }) |
            @Html.ActionLink("Agregar Jugadores", "index", "EquiposJugadores", new { id = item.EquipoID }, null) |
            @Html.ActionLink("Detalles", "Details", new { id = item.EquipoID }) |
            @Html.ActionLink("Dar de Baja", "Delete", new { id = item.EquipoID })
        </td>
    </tr>
}

</table>